ARG DISTRO_ROOT="."
ARG BUILD_CONTAINER="ubuntu:24.04"

FROM ${BUILD_CONTAINER} AS build

RUN apt-get -y update && apt-get -y install make curl
RUN mkdir -p /build

ARG DISTRO_ROOT
COPY ${DISTRO_ROOT}/Makefile /build
COPY ${DISTRO_ROOT}/manifest.yaml /build

WORKDIR /build
RUN make build

FROM ${BUILD_CONTAINER} AS certs
RUN apt-get -y update && apt-get -y install ca-certificates

FROM ${BUILD_CONTAINER}

ARG USER_UID=10001

RUN mkdir -p /etc/{{ .BinaryName }}
RUN chown ${USER_UID}:${USER_UID} /etc/{{ .BinaryName }}

USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build --chmod=755 /build/{{ .BinaryName }} /{{ .BinaryName }}

ARG DISTRO_ROOT
COPY ${DISTRO_ROOT}/config-k8s.yaml /etc/{{ .BinaryName }}/config-k8s.yaml
COPY ${DISTRO_ROOT}/config-standard.yaml /etc/{{ .BinaryName }}/config-standard.yaml
COPY --chmod=755 ${DISTRO_ROOT}/start_otelcol.sh /start_otelcol.sh
ENTRYPOINT ["sh", "/start_otelcol.sh"{{ $length := len .FeatureGates }}{{ if gt $length 0 }}, "--feature-gates={{ .FeatureGates.Render }}"{{ end }}]
CMD ["--config=/etc/{{ .BinaryName }}/config.yaml"]
