# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARG DISTRO_ROOT="."
ARG BUILD_CONTAINER="alpine:3"

FROM ${BUILD_CONTAINER} AS build

RUN apk --update add make curl

ARG DISTRO_ROOT
COPY ${DISTRO_ROOT}/{{ .Name }} /build
COPY ${DISTRO_ROOT}/receiver /receiver
COPY ${DISTRO_ROOT}/processor /processor
COPY ${DISTRO_ROOT}/exporter /exporter
COPY ${DISTRO_ROOT}/extension /extension

WORKDIR /build
RUN make build

FROM ${BUILD_CONTAINER} AS certs
RUN apk --update add ca-certificates

FROM scratch

ARG USER_UID=10001
USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=build --chmod=755 /build/{{ .BinaryName }} /{{ .BinaryName }}
COPY --from=build --chmod=644 /build/config.yaml /etc/{{ .BinaryName }}/config.yaml

ENTRYPOINT ["/{{ .BinaryName }}"{{ $length := len .FeatureGates }}{{ if gt $length 0 }}, "--feature-gates={{ .FeatureGates.Render }}"{{ end }}]
CMD ["--config=/etc/{{ .BinaryName }}/config.yaml"]
