version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: 0.144.0

env:
  - GOWORK=off
  - CGO_ENABLED=0

builds:
  - id: otelcol-google-linux
    env:
    - CGO_ENABLED=1
    - GOEXPERIMENT=boringcrypto
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
      - goos: linux
        goarch: amd64
        env:
          - CC=x86_64-linux-gnu-gcc
    ldflags:
      - "-s"
      - "-w"
      - "-linkmode=external"
      - "-extldflags=-static"
    flags:
      - "-trimpath"
      - "-buildvcs=false"
    binary: otelcol-google
    dir: _build

  - id: otelcol-google-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: otelcol-google
    flags:
      - "-trimpath"
      - "-buildvcs=false"
    dir: _build

nfpms:
  - package_name: otelcol-google
    contents:
      - src: otelcol-google.service
        dst: /lib/systemd/system/otelcol-google.service
      - src: otelcol-google.conf
        dst: /etc/otelcol-google/otelcol-google.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/otelcol-google/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - otelcol-google-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: OpenTelemetry Collector Built By Google
    license: Apache 2.0
