version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: 0.144.0

env:
  - LD_FLAGS=-s -w
  - CGO_ENABLED=0 # TODO: CGO is not supported in goreleaser yet.
  - BUILD_FLAGS=-trimpath
  - GOWORK=off

builds:
  - id: otelcol-google-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: otelcol-google
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

  - id: otelcol-google-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: otelcol-google
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

nfpms:
  - package_name: otelcol-google
    contents:
      - src: otelcol-google.service
        dst: /lib/systemd/system/otelcol-google.service
      - src: otelcol-google.conf
        dst: /etc/otelcol-google/otelcol-google.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/otelcol-google/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - otelcol-google-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: OpenTelemetry Collector Built By Google
    license: Apache 2.0

archives:
  - id: "otelcol-google-tarball"
    ids:
      - "otelcol-google-linux"
      - "otelcol-google-windows"
    formats:
      - "tar.gz"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
        - "zip"

signs:
  - cmd: cosign
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    args:
      - "sign-blob"
      - "--output-signature"
      - "${signature}"
      - "--output-certificate"
      - "${certificate}"
      - "${artifact}"
      - "--yes"
    artifacts: archive
    env:
      - SIGSTORE_NO_CACHE=true
    output: true
