ARG WINDOWS_VERSION=2019
ARG WINBASE=mcr.microsoft.com/windows/servercore:ltsc${WINDOWS_VERSION}
FROM ${WINBASE} AS windows

COPY otelcol-google.exe /otelcol-google.exe
COPY config.yaml /etc/otelcol-google/config.yaml

ENTRYPOINT ["/otelcol-google.exe", "--feature-gates=exporter.googlemanagedprometheus.intToDouble,exporter.googlecloud.CustomMonitoredResources"]
CMD ["--config=/etc/otelcol-google/config.yaml"]
