// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					VarnishBackendConnectionCount: VarnishBackendConnectionCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishBackendConnectionCountMetricAttributeKey{VarnishBackendConnectionCountMetricAttributeKeyBackendConnectionType},
					},
					VarnishBackendRequestCount: VarnishBackendRequestCountMetricConfig{
						Enabled: true,
					},
					VarnishCacheOperationCount: VarnishCacheOperationCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishCacheOperationCountMetricAttributeKey{VarnishCacheOperationCountMetricAttributeKeyCacheOperations},
					},
					VarnishClientRequestCount: VarnishClientRequestCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishClientRequestCountMetricAttributeKey{VarnishClientRequestCountMetricAttributeKeyState},
					},
					VarnishClientRequestErrorCount: VarnishClientRequestErrorCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishClientRequestErrorCountMetricAttributeKey{VarnishClientRequestErrorCountMetricAttributeKeyHTTPStatusCode},
					},
					VarnishObjectCount: VarnishObjectCountMetricConfig{
						Enabled: true,
					},
					VarnishObjectExpired: VarnishObjectExpiredMetricConfig{
						Enabled: true,
					},
					VarnishObjectMoved: VarnishObjectMovedMetricConfig{
						Enabled: true,
					},
					VarnishObjectNuked: VarnishObjectNukedMetricConfig{
						Enabled: true,
					},
					VarnishSessionCount: VarnishSessionCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishSessionCountMetricAttributeKey{VarnishSessionCountMetricAttributeKeySessionType},
					},
					VarnishThreadOperationCount: VarnishThreadOperationCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishThreadOperationCountMetricAttributeKey{VarnishThreadOperationCountMetricAttributeKeyThreadOperations},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					VarnishCacheName: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					VarnishBackendConnectionCount: VarnishBackendConnectionCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishBackendConnectionCountMetricAttributeKey{VarnishBackendConnectionCountMetricAttributeKeyBackendConnectionType},
					},
					VarnishBackendRequestCount: VarnishBackendRequestCountMetricConfig{
						Enabled: false,
					},
					VarnishCacheOperationCount: VarnishCacheOperationCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishCacheOperationCountMetricAttributeKey{VarnishCacheOperationCountMetricAttributeKeyCacheOperations},
					},
					VarnishClientRequestCount: VarnishClientRequestCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishClientRequestCountMetricAttributeKey{VarnishClientRequestCountMetricAttributeKeyState},
					},
					VarnishClientRequestErrorCount: VarnishClientRequestErrorCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishClientRequestErrorCountMetricAttributeKey{VarnishClientRequestErrorCountMetricAttributeKeyHTTPStatusCode},
					},
					VarnishObjectCount: VarnishObjectCountMetricConfig{
						Enabled: false,
					},
					VarnishObjectExpired: VarnishObjectExpiredMetricConfig{
						Enabled: false,
					},
					VarnishObjectMoved: VarnishObjectMovedMetricConfig{
						Enabled: false,
					},
					VarnishObjectNuked: VarnishObjectNukedMetricConfig{
						Enabled: false,
					},
					VarnishSessionCount: VarnishSessionCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishSessionCountMetricAttributeKey{VarnishSessionCountMetricAttributeKeySessionType},
					},
					VarnishThreadOperationCount: VarnishThreadOperationCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []VarnishThreadOperationCountMetricAttributeKey{VarnishThreadOperationCountMetricAttributeKeyThreadOperations},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					VarnishCacheName: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(VarnishBackendConnectionCountMetricConfig{}, VarnishBackendRequestCountMetricConfig{}, VarnishCacheOperationCountMetricConfig{}, VarnishClientRequestCountMetricConfig{}, VarnishClientRequestErrorCountMetricConfig{}, VarnishObjectCountMetricConfig{}, VarnishObjectExpiredMetricConfig{}, VarnishObjectMovedMetricConfig{}, VarnishObjectNukedMetricConfig{}, VarnishSessionCountMetricConfig{}, VarnishThreadOperationCountMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestVarnishBackendConnectionCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishBackendConnectionCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishBackendConnectionCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.backend.connection.count doesn't have an attribute invalid, valid attributes: [kind]")

	cfg = DefaultMetricsConfig().VarnishBackendConnectionCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestVarnishCacheOperationCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishCacheOperationCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishCacheOperationCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.cache.operation.count doesn't have an attribute invalid, valid attributes: [operation]")

	cfg = DefaultMetricsConfig().VarnishCacheOperationCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestVarnishClientRequestCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishClientRequestCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishClientRequestCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.client.request.count doesn't have an attribute invalid, valid attributes: [state]")

	cfg = DefaultMetricsConfig().VarnishClientRequestCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestVarnishClientRequestErrorCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishClientRequestErrorCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishClientRequestErrorCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.client.request.error.count doesn't have an attribute invalid, valid attributes: [status_code]")

	cfg = DefaultMetricsConfig().VarnishClientRequestErrorCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestVarnishSessionCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishSessionCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishSessionCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.session.count doesn't have an attribute invalid, valid attributes: [kind]")

	cfg = DefaultMetricsConfig().VarnishSessionCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestVarnishThreadOperationCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().VarnishThreadOperationCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []VarnishThreadOperationCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric varnish.thread.operation.count doesn't have an attribute invalid, valid attributes: [operation]")

	cfg = DefaultMetricsConfig().VarnishThreadOperationCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				VarnishCacheName: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				VarnishCacheName: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
