allowedLicenses:
  - Apache-2.0
ignoreFiles:
  - "**/**/generated_*.go"
  - receiver/mongodbreceiver/**/*.go
  - receiver/prometheusreceiver/**/*.go
  - exporter/googlemanagedprometheusexporter/**/*.go
sourceFileExtensions:
  - go
  - ps1
  - sh
