allowedLicenses:
  - Apache-2.0
ignoreFiles:
  - receiver/**/generated_metrics.go
  - receiver/**/generated_metrics_test.go
  - receiver/**/generated_config.go
  - receiver/**/generated_config_test.go
  - receiver/**/generated_status.go
  - receiver/mongodbreceiver/**/*.go
  - receiver/prometheusreceiver/**/*.go
sourceFileExtensions:
  - go
  - ps1
  - sh
