// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					GpuDcgmClockFrequency: GpuDcgmClockFrequencyMetricConfig{
						Enabled: true,
					},
					GpuDcgmClockThrottleDurationTime: GpuDcgmClockThrottleDurationTimeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmClockThrottleDurationTimeMetricAttributeKey{GpuDcgmClockThrottleDurationTimeMetricAttributeKeyGpuClockViolation},
					},
					GpuDcgmCodecDecoderUtilization: GpuDcgmCodecDecoderUtilizationMetricConfig{
						Enabled: true,
					},
					GpuDcgmCodecEncoderUtilization: GpuDcgmCodecEncoderUtilizationMetricConfig{
						Enabled: true,
					},
					GpuDcgmEccErrors: GpuDcgmEccErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmEccErrorsMetricAttributeKey{GpuDcgmEccErrorsMetricAttributeKeyGpuErrorType},
					},
					GpuDcgmEnergyConsumption: GpuDcgmEnergyConsumptionMetricConfig{
						Enabled: true,
					},
					GpuDcgmMemoryBandwidthUtilization: GpuDcgmMemoryBandwidthUtilizationMetricConfig{
						Enabled: true,
					},
					GpuDcgmMemoryBytesUsed: GpuDcgmMemoryBytesUsedMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []GpuDcgmMemoryBytesUsedMetricAttributeKey{GpuDcgmMemoryBytesUsedMetricAttributeKeyGpuMemoryState},
					},
					GpuDcgmNvlinkIo: GpuDcgmNvlinkIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmNvlinkIoMetricAttributeKey{GpuDcgmNvlinkIoMetricAttributeKeyNetworkIoDirection},
					},
					GpuDcgmPcieIo: GpuDcgmPcieIoMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmPcieIoMetricAttributeKey{GpuDcgmPcieIoMetricAttributeKeyNetworkIoDirection},
					},
					GpuDcgmPipeUtilization: GpuDcgmPipeUtilizationMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []GpuDcgmPipeUtilizationMetricAttributeKey{GpuDcgmPipeUtilizationMetricAttributeKeyGpuPipe},
					},
					GpuDcgmSmOccupancy: GpuDcgmSmOccupancyMetricConfig{
						Enabled: true,
					},
					GpuDcgmSmUtilization: GpuDcgmSmUtilizationMetricConfig{
						Enabled: true,
					},
					GpuDcgmTemperature: GpuDcgmTemperatureMetricConfig{
						Enabled: true,
					},
					GpuDcgmUtilization: GpuDcgmUtilizationMetricConfig{
						Enabled: true,
					},
					GpuDcgmXidErrors: GpuDcgmXidErrorsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmXidErrorsMetricAttributeKey{GpuDcgmXidErrorsMetricAttributeKeyGpuErrorXid},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					GpuModel:  ResourceAttributeConfig{Enabled: true},
					GpuNumber: ResourceAttributeConfig{Enabled: true},
					GpuUUID:   ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					GpuDcgmClockFrequency: GpuDcgmClockFrequencyMetricConfig{
						Enabled: false,
					},
					GpuDcgmClockThrottleDurationTime: GpuDcgmClockThrottleDurationTimeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmClockThrottleDurationTimeMetricAttributeKey{GpuDcgmClockThrottleDurationTimeMetricAttributeKeyGpuClockViolation},
					},
					GpuDcgmCodecDecoderUtilization: GpuDcgmCodecDecoderUtilizationMetricConfig{
						Enabled: false,
					},
					GpuDcgmCodecEncoderUtilization: GpuDcgmCodecEncoderUtilizationMetricConfig{
						Enabled: false,
					},
					GpuDcgmEccErrors: GpuDcgmEccErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmEccErrorsMetricAttributeKey{GpuDcgmEccErrorsMetricAttributeKeyGpuErrorType},
					},
					GpuDcgmEnergyConsumption: GpuDcgmEnergyConsumptionMetricConfig{
						Enabled: false,
					},
					GpuDcgmMemoryBandwidthUtilization: GpuDcgmMemoryBandwidthUtilizationMetricConfig{
						Enabled: false,
					},
					GpuDcgmMemoryBytesUsed: GpuDcgmMemoryBytesUsedMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []GpuDcgmMemoryBytesUsedMetricAttributeKey{GpuDcgmMemoryBytesUsedMetricAttributeKeyGpuMemoryState},
					},
					GpuDcgmNvlinkIo: GpuDcgmNvlinkIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmNvlinkIoMetricAttributeKey{GpuDcgmNvlinkIoMetricAttributeKeyNetworkIoDirection},
					},
					GpuDcgmPcieIo: GpuDcgmPcieIoMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmPcieIoMetricAttributeKey{GpuDcgmPcieIoMetricAttributeKeyNetworkIoDirection},
					},
					GpuDcgmPipeUtilization: GpuDcgmPipeUtilizationMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategyAvg,
						EnabledAttributes:   []GpuDcgmPipeUtilizationMetricAttributeKey{GpuDcgmPipeUtilizationMetricAttributeKeyGpuPipe},
					},
					GpuDcgmSmOccupancy: GpuDcgmSmOccupancyMetricConfig{
						Enabled: false,
					},
					GpuDcgmSmUtilization: GpuDcgmSmUtilizationMetricConfig{
						Enabled: false,
					},
					GpuDcgmTemperature: GpuDcgmTemperatureMetricConfig{
						Enabled: false,
					},
					GpuDcgmUtilization: GpuDcgmUtilizationMetricConfig{
						Enabled: false,
					},
					GpuDcgmXidErrors: GpuDcgmXidErrorsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []GpuDcgmXidErrorsMetricAttributeKey{GpuDcgmXidErrorsMetricAttributeKeyGpuErrorXid},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					GpuModel:  ResourceAttributeConfig{Enabled: false},
					GpuNumber: ResourceAttributeConfig{Enabled: false},
					GpuUUID:   ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(GpuDcgmClockFrequencyMetricConfig{}, GpuDcgmClockThrottleDurationTimeMetricConfig{}, GpuDcgmCodecDecoderUtilizationMetricConfig{}, GpuDcgmCodecEncoderUtilizationMetricConfig{}, GpuDcgmEccErrorsMetricConfig{}, GpuDcgmEnergyConsumptionMetricConfig{}, GpuDcgmMemoryBandwidthUtilizationMetricConfig{}, GpuDcgmMemoryBytesUsedMetricConfig{}, GpuDcgmNvlinkIoMetricConfig{}, GpuDcgmPcieIoMetricConfig{}, GpuDcgmPipeUtilizationMetricConfig{}, GpuDcgmSmOccupancyMetricConfig{}, GpuDcgmSmUtilizationMetricConfig{}, GpuDcgmTemperatureMetricConfig{}, GpuDcgmUtilizationMetricConfig{}, GpuDcgmXidErrorsMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				GpuModel:  ResourceAttributeConfig{Enabled: true},
				GpuNumber: ResourceAttributeConfig{Enabled: true},
				GpuUUID:   ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				GpuModel:  ResourceAttributeConfig{Enabled: false},
				GpuNumber: ResourceAttributeConfig{Enabled: false},
				GpuUUID:   ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
