steps:
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
  - gcloud
  - config
  - get-value
  - project
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - '-t'
  - gboc-e2e
  - ./e2e_test
  id: Build tester image
- name: gboc-e2e
  args:
  - '-c'
  - |
    gcloud config get-value project
  id: Test project location - gboc
  entrypoint: /bin/bash
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'config', 'get-value', 'project']
  id: Test project location - gcloud
- name: gboc-e2e
  env:
  - PROJECT_NAME=$_PROJECT_NAME
  - USE_INTERNAL_IP="true"
  - >-
    SERVICE_EMAIL=build-and-test@stackdriver-test-143416.iam.gserviceaccount.com
  args:
  - '-c'
  - |
    cd ./e2e_test
    echo ${_BUILD_ARTIFACTS}
    gcloud config get-value project
    go test e2e_test.go -timeout=3h -tags integration_test
  entrypoint: /bin/bash
logsBucket: 'gs://cloud-built-otel-collector-buckets-test-logs'
substitutions:
  _PROJECT_NAME: ''
  _BUILD_ARTIFACTS: ''
