// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: NewDefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MongodbCacheOperations: MongodbCacheOperationsMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbCacheOperationsMetricAttributeKey{MongodbCacheOperationsMetricAttributeKeyType},
					},
					MongodbCollectionCount: MongodbCollectionCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbCollectionCountMetricAttributeKey{MongodbCollectionCountMetricAttributeKeyDatabase},
					},
					MongodbConnectionCount: MongodbConnectionCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbConnectionCountMetricAttributeKey{MongodbConnectionCountMetricAttributeKeyDatabase, MongodbConnectionCountMetricAttributeKeyConnectionType},
					},
					MongodbCursorCount: MongodbCursorCountMetricConfig{
						Enabled: true,
					},
					MongodbCursorTimeoutCount: MongodbCursorTimeoutCountMetricConfig{
						Enabled: true,
					},
					MongodbDataSize: MongodbDataSizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbDataSizeMetricAttributeKey{MongodbDataSizeMetricAttributeKeyDatabase},
					},
					MongodbDatabaseCount: MongodbDatabaseCountMetricConfig{
						Enabled: true,
					},
					MongodbDocumentOperationCount: MongodbDocumentOperationCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbDocumentOperationCountMetricAttributeKey{MongodbDocumentOperationCountMetricAttributeKeyDatabase, MongodbDocumentOperationCountMetricAttributeKeyOperation},
					},
					MongodbExtentCount: MongodbExtentCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbExtentCountMetricAttributeKey{MongodbExtentCountMetricAttributeKeyDatabase},
					},
					MongodbGlobalLockTime: MongodbGlobalLockTimeMetricConfig{
						Enabled: true,
					},
					MongodbIndexAccessCount: MongodbIndexAccessCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexAccessCountMetricAttributeKey{MongodbIndexAccessCountMetricAttributeKeyDatabase, MongodbIndexAccessCountMetricAttributeKeyCollection},
					},
					MongodbIndexCount: MongodbIndexCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexCountMetricAttributeKey{MongodbIndexCountMetricAttributeKeyDatabase},
					},
					MongodbIndexSize: MongodbIndexSizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexSizeMetricAttributeKey{MongodbIndexSizeMetricAttributeKeyDatabase},
					},
					MongodbLockAcquireCount: MongodbLockAcquireCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireCountMetricAttributeKey{MongodbLockAcquireCountMetricAttributeKeyDatabase, MongodbLockAcquireCountMetricAttributeKeyLockType, MongodbLockAcquireCountMetricAttributeKeyLockMode},
					},
					MongodbLockAcquireTime: MongodbLockAcquireTimeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireTimeMetricAttributeKey{MongodbLockAcquireTimeMetricAttributeKeyDatabase, MongodbLockAcquireTimeMetricAttributeKeyLockType, MongodbLockAcquireTimeMetricAttributeKeyLockMode},
					},
					MongodbLockAcquireWaitCount: MongodbLockAcquireWaitCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireWaitCountMetricAttributeKey{MongodbLockAcquireWaitCountMetricAttributeKeyDatabase, MongodbLockAcquireWaitCountMetricAttributeKeyLockType, MongodbLockAcquireWaitCountMetricAttributeKeyLockMode},
					},
					MongodbLockDeadlockCount: MongodbLockDeadlockCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockDeadlockCountMetricAttributeKey{MongodbLockDeadlockCountMetricAttributeKeyDatabase, MongodbLockDeadlockCountMetricAttributeKeyLockType, MongodbLockDeadlockCountMetricAttributeKeyLockMode},
					},
					MongodbMemoryUsage: MongodbMemoryUsageMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbMemoryUsageMetricAttributeKey{MongodbMemoryUsageMetricAttributeKeyDatabase, MongodbMemoryUsageMetricAttributeKeyMemoryType},
					},
					MongodbNetworkIoReceive: MongodbNetworkIoReceiveMetricConfig{
						Enabled: true,
					},
					MongodbNetworkIoTransmit: MongodbNetworkIoTransmitMetricConfig{
						Enabled: true,
					},
					MongodbNetworkRequestCount: MongodbNetworkRequestCountMetricConfig{
						Enabled: true,
					},
					MongodbObjectCount: MongodbObjectCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbObjectCountMetricAttributeKey{MongodbObjectCountMetricAttributeKeyDatabase},
					},
					MongodbOperationCount: MongodbOperationCountMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbOperationCountMetricAttributeKey{MongodbOperationCountMetricAttributeKeyOperation},
					},
					MongodbOperationTime: MongodbOperationTimeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbOperationTimeMetricAttributeKey{MongodbOperationTimeMetricAttributeKeyOperation},
					},
					MongodbSessionCount: MongodbSessionCountMetricConfig{
						Enabled: true,
					},
					MongodbStorageSize: MongodbStorageSizeMetricConfig{
						Enabled:             true,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbStorageSizeMetricAttributeKey{MongodbStorageSizeMetricAttributeKeyDatabase},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					Database: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					MongodbCacheOperations: MongodbCacheOperationsMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbCacheOperationsMetricAttributeKey{MongodbCacheOperationsMetricAttributeKeyType},
					},
					MongodbCollectionCount: MongodbCollectionCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbCollectionCountMetricAttributeKey{MongodbCollectionCountMetricAttributeKeyDatabase},
					},
					MongodbConnectionCount: MongodbConnectionCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbConnectionCountMetricAttributeKey{MongodbConnectionCountMetricAttributeKeyDatabase, MongodbConnectionCountMetricAttributeKeyConnectionType},
					},
					MongodbCursorCount: MongodbCursorCountMetricConfig{
						Enabled: false,
					},
					MongodbCursorTimeoutCount: MongodbCursorTimeoutCountMetricConfig{
						Enabled: false,
					},
					MongodbDataSize: MongodbDataSizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbDataSizeMetricAttributeKey{MongodbDataSizeMetricAttributeKeyDatabase},
					},
					MongodbDatabaseCount: MongodbDatabaseCountMetricConfig{
						Enabled: false,
					},
					MongodbDocumentOperationCount: MongodbDocumentOperationCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbDocumentOperationCountMetricAttributeKey{MongodbDocumentOperationCountMetricAttributeKeyDatabase, MongodbDocumentOperationCountMetricAttributeKeyOperation},
					},
					MongodbExtentCount: MongodbExtentCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbExtentCountMetricAttributeKey{MongodbExtentCountMetricAttributeKeyDatabase},
					},
					MongodbGlobalLockTime: MongodbGlobalLockTimeMetricConfig{
						Enabled: false,
					},
					MongodbIndexAccessCount: MongodbIndexAccessCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexAccessCountMetricAttributeKey{MongodbIndexAccessCountMetricAttributeKeyDatabase, MongodbIndexAccessCountMetricAttributeKeyCollection},
					},
					MongodbIndexCount: MongodbIndexCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexCountMetricAttributeKey{MongodbIndexCountMetricAttributeKeyDatabase},
					},
					MongodbIndexSize: MongodbIndexSizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbIndexSizeMetricAttributeKey{MongodbIndexSizeMetricAttributeKeyDatabase},
					},
					MongodbLockAcquireCount: MongodbLockAcquireCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireCountMetricAttributeKey{MongodbLockAcquireCountMetricAttributeKeyDatabase, MongodbLockAcquireCountMetricAttributeKeyLockType, MongodbLockAcquireCountMetricAttributeKeyLockMode},
					},
					MongodbLockAcquireTime: MongodbLockAcquireTimeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireTimeMetricAttributeKey{MongodbLockAcquireTimeMetricAttributeKeyDatabase, MongodbLockAcquireTimeMetricAttributeKeyLockType, MongodbLockAcquireTimeMetricAttributeKeyLockMode},
					},
					MongodbLockAcquireWaitCount: MongodbLockAcquireWaitCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockAcquireWaitCountMetricAttributeKey{MongodbLockAcquireWaitCountMetricAttributeKeyDatabase, MongodbLockAcquireWaitCountMetricAttributeKeyLockType, MongodbLockAcquireWaitCountMetricAttributeKeyLockMode},
					},
					MongodbLockDeadlockCount: MongodbLockDeadlockCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbLockDeadlockCountMetricAttributeKey{MongodbLockDeadlockCountMetricAttributeKeyDatabase, MongodbLockDeadlockCountMetricAttributeKeyLockType, MongodbLockDeadlockCountMetricAttributeKeyLockMode},
					},
					MongodbMemoryUsage: MongodbMemoryUsageMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbMemoryUsageMetricAttributeKey{MongodbMemoryUsageMetricAttributeKeyDatabase, MongodbMemoryUsageMetricAttributeKeyMemoryType},
					},
					MongodbNetworkIoReceive: MongodbNetworkIoReceiveMetricConfig{
						Enabled: false,
					},
					MongodbNetworkIoTransmit: MongodbNetworkIoTransmitMetricConfig{
						Enabled: false,
					},
					MongodbNetworkRequestCount: MongodbNetworkRequestCountMetricConfig{
						Enabled: false,
					},
					MongodbObjectCount: MongodbObjectCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbObjectCountMetricAttributeKey{MongodbObjectCountMetricAttributeKeyDatabase},
					},
					MongodbOperationCount: MongodbOperationCountMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbOperationCountMetricAttributeKey{MongodbOperationCountMetricAttributeKeyOperation},
					},
					MongodbOperationTime: MongodbOperationTimeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbOperationTimeMetricAttributeKey{MongodbOperationTimeMetricAttributeKeyOperation},
					},
					MongodbSessionCount: MongodbSessionCountMetricConfig{
						Enabled: false,
					},
					MongodbStorageSize: MongodbStorageSizeMetricConfig{
						Enabled:             false,
						AggregationStrategy: AggregationStrategySum,
						EnabledAttributes:   []MongodbStorageSizeMetricAttributeKey{MongodbStorageSizeMetricAttributeKeyDatabase},
					},
				},
				ResourceAttributes: ResourceAttributesConfig{
					Database: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MongodbCacheOperationsMetricConfig{}, MongodbCollectionCountMetricConfig{}, MongodbConnectionCountMetricConfig{}, MongodbCursorCountMetricConfig{}, MongodbCursorTimeoutCountMetricConfig{}, MongodbDataSizeMetricConfig{}, MongodbDatabaseCountMetricConfig{}, MongodbDocumentOperationCountMetricConfig{}, MongodbExtentCountMetricConfig{}, MongodbGlobalLockTimeMetricConfig{}, MongodbIndexAccessCountMetricConfig{}, MongodbIndexCountMetricConfig{}, MongodbIndexSizeMetricConfig{}, MongodbLockAcquireCountMetricConfig{}, MongodbLockAcquireTimeMetricConfig{}, MongodbLockAcquireWaitCountMetricConfig{}, MongodbLockDeadlockCountMetricConfig{}, MongodbMemoryUsageMetricConfig{}, MongodbNetworkIoReceiveMetricConfig{}, MongodbNetworkIoTransmitMetricConfig{}, MongodbNetworkRequestCountMetricConfig{}, MongodbObjectCountMetricConfig{}, MongodbOperationCountMetricConfig{}, MongodbOperationTimeMetricConfig{}, MongodbSessionCountMetricConfig{}, MongodbStorageSizeMetricConfig{}, ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}
func TestMongodbCacheOperationsMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbCacheOperations
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbCacheOperationsMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.cache.operations doesn't have an attribute invalid, valid attributes: [type]")

	cfg = DefaultMetricsConfig().MongodbCacheOperations
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbCollectionCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbCollectionCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbCollectionCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.collection.count doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbCollectionCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbConnectionCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbConnectionCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbConnectionCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.connection.count doesn't have an attribute invalid, valid attributes: [database, type]")

	cfg = DefaultMetricsConfig().MongodbConnectionCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbDataSizeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbDataSize
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbDataSizeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.data.size doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbDataSize
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbDocumentOperationCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbDocumentOperationCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbDocumentOperationCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.document.operation.count doesn't have an attribute invalid, valid attributes: [database, operation]")

	cfg = DefaultMetricsConfig().MongodbDocumentOperationCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbExtentCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbExtentCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbExtentCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.extent.count doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbExtentCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbIndexAccessCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbIndexAccessCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbIndexAccessCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.index.access.count doesn't have an attribute invalid, valid attributes: [database, collection]")

	cfg = DefaultMetricsConfig().MongodbIndexAccessCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbIndexCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbIndexCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbIndexCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.index.count doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbIndexCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbIndexSizeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbIndexSize
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbIndexSizeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.index.size doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbIndexSize
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbLockAcquireCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbLockAcquireCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbLockAcquireCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.lock.acquire.count doesn't have an attribute invalid, valid attributes: [database, lock_type, lock_mode]")

	cfg = DefaultMetricsConfig().MongodbLockAcquireCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbLockAcquireTimeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbLockAcquireTime
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbLockAcquireTimeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.lock.acquire.time doesn't have an attribute invalid, valid attributes: [database, lock_type, lock_mode]")

	cfg = DefaultMetricsConfig().MongodbLockAcquireTime
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbLockAcquireWaitCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbLockAcquireWaitCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbLockAcquireWaitCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.lock.acquire.wait_count doesn't have an attribute invalid, valid attributes: [database, lock_type, lock_mode]")

	cfg = DefaultMetricsConfig().MongodbLockAcquireWaitCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbLockDeadlockCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbLockDeadlockCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbLockDeadlockCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.lock.deadlock.count doesn't have an attribute invalid, valid attributes: [database, lock_type, lock_mode]")

	cfg = DefaultMetricsConfig().MongodbLockDeadlockCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbMemoryUsageMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbMemoryUsage
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbMemoryUsageMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.memory.usage doesn't have an attribute invalid, valid attributes: [database, type]")

	cfg = DefaultMetricsConfig().MongodbMemoryUsage
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbObjectCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbObjectCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbObjectCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.object.count doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbObjectCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbOperationCountMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbOperationCount
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbOperationCountMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.operation.count doesn't have an attribute invalid, valid attributes: [operation]")

	cfg = DefaultMetricsConfig().MongodbOperationCount
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbOperationTimeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbOperationTime
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbOperationTimeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.operation.time doesn't have an attribute invalid, valid attributes: [operation]")

	cfg = DefaultMetricsConfig().MongodbOperationTime
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func TestMongodbStorageSizeMetricsConfig_Validate(t *testing.T) {
	cfg := DefaultMetricsConfig().MongodbStorageSize
	require.NoError(t, cfg.Validate())

	cfg.EnabledAttributes = []MongodbStorageSizeMetricAttributeKey{"invalid"}
	require.ErrorContains(t, cfg.Validate(), "metric mongodb.storage.size doesn't have an attribute invalid, valid attributes: [database]")

	cfg = DefaultMetricsConfig().MongodbStorageSize
	cfg.AggregationStrategy = "invalid"
	require.ErrorContains(t, cfg.Validate(), "invalid aggregation strategy")
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := NewDefaultMetricsBuilderConfig()
	require.NoError(t, sub.Unmarshal(&cfg, confmap.WithIgnoreUnused()))
	return cfg
}

func TestResourceAttributesConfig(t *testing.T) {
	tests := []struct {
		name string
		want ResourceAttributesConfig
	}{
		{
			name: "default",
			want: DefaultResourceAttributesConfig(),
		},
		{
			name: "all_set",
			want: ResourceAttributesConfig{
				Database: ResourceAttributeConfig{Enabled: true},
			},
		},
		{
			name: "none_set",
			want: ResourceAttributesConfig{
				Database: ResourceAttributeConfig{Enabled: false},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadResourceAttributesConfig(t, tt.name)
			diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(ResourceAttributeConfig{}))
			require.Emptyf(t, diff, "Config mismatch (-expected +actual):\n%s", diff)
		})
	}
}

func loadResourceAttributesConfig(t *testing.T, name string) ResourceAttributesConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	sub, err = sub.Sub("resource_attributes")
	require.NoError(t, err)
	cfg := DefaultResourceAttributesConfig()
	require.NoError(t, sub.Unmarshal(&cfg))
	return cfg
}
