// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
	testDataSetReag
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "reaggregate_set",
			metricsSet:  testDataSetReag,
			resAttrsSet: testDataSetReag,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))
			aggMap := make(map[string]string) // contains the aggregation strategies for each metric name
			aggMap["nvml.gpu.memory.bytes_used"] = mb.metricNvmlGpuMemoryBytesUsed.config.AggregationStrategy
			aggMap["nvml.gpu.processes.max_bytes_used"] = mb.metricNvmlGpuProcessesMaxBytesUsed.config.AggregationStrategy
			aggMap["nvml.gpu.processes.utilization"] = mb.metricNvmlGpuProcessesUtilization.config.AggregationStrategy
			aggMap["nvml.gpu.utilization"] = mb.metricNvmlGpuUtilization.config.AggregationStrategy

			expectedWarnings := 0
			if tt.metricsSet != testDataSetReag {
				assert.Equal(t, expectedWarnings, observedLogs.Len())
			}

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNvmlGpuMemoryBytesUsedDataPoint(ts, 1, "model-val", "gpu_number-val", "uuid-val", AttributeMemoryStateUsed)
			if tt.name == "reaggregate_set" {
				mb.RecordNvmlGpuMemoryBytesUsedDataPoint(ts, 3, "model-val-2", "gpu_number-val-2", "uuid-val-2", AttributeMemoryStateFree)
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNvmlGpuProcessesMaxBytesUsedDataPoint(ts, 1, "model-val", "gpu_number-val", "uuid-val", 3, "process-val", "command-val", "command_line-val", "owner-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNvmlGpuProcessesMaxBytesUsedDataPoint(ts, 3, "model-val-2", "gpu_number-val-2", "uuid-val-2", 4, "process-val-2", "command-val-2", "command_line-val-2", "owner-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNvmlGpuProcessesUtilizationDataPoint(ts, 1, "model-val", "gpu_number-val", "uuid-val", 3, "process-val", "command-val", "command_line-val", "owner-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNvmlGpuProcessesUtilizationDataPoint(ts, 3, "model-val-2", "gpu_number-val-2", "uuid-val-2", 4, "process-val-2", "command-val-2", "command_line-val-2", "owner-val-2")
			}

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordNvmlGpuUtilizationDataPoint(ts, 1, "model-val", "gpu_number-val", "uuid-val")
			if tt.name == "reaggregate_set" {
				mb.RecordNvmlGpuUtilizationDataPoint(ts, 3, "model-val-2", "gpu_number-val-2", "uuid-val-2")
			}

			res := pcommon.NewResource()
			metrics := mb.Emit(WithResource(res))
			if tt.name == "reaggregate_set" {
				assert.Empty(t, mb.metricNvmlGpuMemoryBytesUsed.aggDataPoints)
				assert.Empty(t, mb.metricNvmlGpuProcessesMaxBytesUsed.aggDataPoints)
				assert.Empty(t, mb.metricNvmlGpuProcessesUtilization.aggDataPoints)
				assert.Empty(t, mb.metricNvmlGpuUtilization.aggDataPoints)
			}

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			var allMetricsList []pmetric.Metric
			totalMetricsCount := 0
			for ri := 0; ri < metrics.ResourceMetrics().Len(); ri++ {
				rm := metrics.ResourceMetrics().At(ri)
				assert.Equal(t, 1, rm.ScopeMetrics().Len())
				ms := rm.ScopeMetrics().At(0).Metrics()
				totalMetricsCount += ms.Len()
				for mi := 0; mi < ms.Len(); mi++ {
					allMetricsList = append(allMetricsList, ms.At(mi))
				}
			}
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, totalMetricsCount)
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, totalMetricsCount)
			}
			validatedMetrics := make(map[string]bool)
			for _, mi := range allMetricsList {
				switch mi.Name() {
				case "nvml.gpu.memory.bytes_used":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["nvml.gpu.memory.bytes_used"], "Found a duplicate in the metrics slice: nvml.gpu.memory.bytes_used")
						validatedMetrics["nvml.gpu.memory.bytes_used"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current number of GPU memory bytes used by state. Summing the values of all states yields the total GPU memory space.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						modelAttrVal, ok := dp.Attributes().Get("model")
						assert.True(t, ok)
						assert.Equal(t, "model-val", modelAttrVal.Str())
						gpuNumberAttrVal, ok := dp.Attributes().Get("gpu_number")
						assert.True(t, ok)
						assert.Equal(t, "gpu_number-val", gpuNumberAttrVal.Str())
						uuidAttrVal, ok := dp.Attributes().Get("uuid")
						assert.True(t, ok)
						assert.Equal(t, "uuid-val", uuidAttrVal.Str())
						memoryStateAttrVal, ok := dp.Attributes().Get("memory_state")
						assert.True(t, ok)
						assert.Equal(t, "used", memoryStateAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["nvml.gpu.memory.bytes_used"], "Found a duplicate in the metrics slice: nvml.gpu.memory.bytes_used")
						validatedMetrics["nvml.gpu.memory.bytes_used"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Current number of GPU memory bytes used by state. Summing the values of all states yields the total GPU memory space.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["nvml.gpu.memory.bytes_used"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("model")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("gpu_number")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("uuid")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("memory_state")
						assert.False(t, ok)
					}
				case "nvml.gpu.processes.max_bytes_used":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["nvml.gpu.processes.max_bytes_used"], "Found a duplicate in the metrics slice: nvml.gpu.processes.max_bytes_used")
						validatedMetrics["nvml.gpu.processes.max_bytes_used"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum total GPU memory in bytes that was ever allocated by the process.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						assert.Equal(t, int64(1), dp.IntValue())
						modelAttrVal, ok := dp.Attributes().Get("model")
						assert.True(t, ok)
						assert.Equal(t, "model-val", modelAttrVal.Str())
						gpuNumberAttrVal, ok := dp.Attributes().Get("gpu_number")
						assert.True(t, ok)
						assert.Equal(t, "gpu_number-val", gpuNumberAttrVal.Str())
						uuidAttrVal, ok := dp.Attributes().Get("uuid")
						assert.True(t, ok)
						assert.Equal(t, "uuid-val", uuidAttrVal.Str())
						pidAttrVal, ok := dp.Attributes().Get("pid")
						assert.True(t, ok)
						assert.EqualValues(t, 3, pidAttrVal.Int())
						processAttrVal, ok := dp.Attributes().Get("process")
						assert.True(t, ok)
						assert.Equal(t, "process-val", processAttrVal.Str())
						commandAttrVal, ok := dp.Attributes().Get("command")
						assert.True(t, ok)
						assert.Equal(t, "command-val", commandAttrVal.Str())
						commandLineAttrVal, ok := dp.Attributes().Get("command_line")
						assert.True(t, ok)
						assert.Equal(t, "command_line-val", commandLineAttrVal.Str())
						ownerAttrVal, ok := dp.Attributes().Get("owner")
						assert.True(t, ok)
						assert.Equal(t, "owner-val", ownerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["nvml.gpu.processes.max_bytes_used"], "Found a duplicate in the metrics slice: nvml.gpu.processes.max_bytes_used")
						validatedMetrics["nvml.gpu.processes.max_bytes_used"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Maximum total GPU memory in bytes that was ever allocated by the process.", mi.Description())
						assert.Equal(t, "By", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
						switch aggMap["nvml.gpu.processes.max_bytes_used"] {
						case "sum":
							assert.Equal(t, int64(4), dp.IntValue())
						case "avg":
							assert.Equal(t, int64(2), dp.IntValue())
						case "min":
							assert.Equal(t, int64(1), dp.IntValue())
						case "max":
							assert.Equal(t, int64(3), dp.IntValue())
						}
						_, ok := dp.Attributes().Get("model")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("gpu_number")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("uuid")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("pid")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("process")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("command")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("command_line")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("owner")
						assert.False(t, ok)
					}
				case "nvml.gpu.processes.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["nvml.gpu.processes.utilization"], "Found a duplicate in the metrics slice: nvml.gpu.processes.utilization")
						validatedMetrics["nvml.gpu.processes.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time over the process's life thus far during which one or more kernels was executing on the GPU.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						modelAttrVal, ok := dp.Attributes().Get("model")
						assert.True(t, ok)
						assert.Equal(t, "model-val", modelAttrVal.Str())
						gpuNumberAttrVal, ok := dp.Attributes().Get("gpu_number")
						assert.True(t, ok)
						assert.Equal(t, "gpu_number-val", gpuNumberAttrVal.Str())
						uuidAttrVal, ok := dp.Attributes().Get("uuid")
						assert.True(t, ok)
						assert.Equal(t, "uuid-val", uuidAttrVal.Str())
						pidAttrVal, ok := dp.Attributes().Get("pid")
						assert.True(t, ok)
						assert.EqualValues(t, 3, pidAttrVal.Int())
						processAttrVal, ok := dp.Attributes().Get("process")
						assert.True(t, ok)
						assert.Equal(t, "process-val", processAttrVal.Str())
						commandAttrVal, ok := dp.Attributes().Get("command")
						assert.True(t, ok)
						assert.Equal(t, "command-val", commandAttrVal.Str())
						commandLineAttrVal, ok := dp.Attributes().Get("command_line")
						assert.True(t, ok)
						assert.Equal(t, "command_line-val", commandLineAttrVal.Str())
						ownerAttrVal, ok := dp.Attributes().Get("owner")
						assert.True(t, ok)
						assert.Equal(t, "owner-val", ownerAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["nvml.gpu.processes.utilization"], "Found a duplicate in the metrics slice: nvml.gpu.processes.utilization")
						validatedMetrics["nvml.gpu.processes.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time over the process's life thus far during which one or more kernels was executing on the GPU.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["nvml.gpu.processes.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("model")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("gpu_number")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("uuid")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("pid")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("process")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("command")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("command_line")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("owner")
						assert.False(t, ok)
					}
				case "nvml.gpu.utilization":
					if tt.name != "reaggregate_set" {
						assert.False(t, validatedMetrics["nvml.gpu.utilization"], "Found a duplicate in the metrics slice: nvml.gpu.utilization")
						validatedMetrics["nvml.gpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time GPU was not idle since the last sample.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						modelAttrVal, ok := dp.Attributes().Get("model")
						assert.True(t, ok)
						assert.Equal(t, "model-val", modelAttrVal.Str())
						gpuNumberAttrVal, ok := dp.Attributes().Get("gpu_number")
						assert.True(t, ok)
						assert.Equal(t, "gpu_number-val", gpuNumberAttrVal.Str())
						uuidAttrVal, ok := dp.Attributes().Get("uuid")
						assert.True(t, ok)
						assert.Equal(t, "uuid-val", uuidAttrVal.Str())
					} else {
						assert.False(t, validatedMetrics["nvml.gpu.utilization"], "Found a duplicate in the metrics slice: nvml.gpu.utilization")
						validatedMetrics["nvml.gpu.utilization"] = true
						assert.Equal(t, pmetric.MetricTypeGauge, mi.Type())
						assert.Equal(t, 1, mi.Gauge().DataPoints().Len())
						assert.Equal(t, "Fraction of time GPU was not idle since the last sample.", mi.Description())
						assert.Equal(t, "1", mi.Unit())
						dp := mi.Gauge().DataPoints().At(0)
						assert.Equal(t, start, dp.StartTimestamp())
						assert.Equal(t, ts, dp.Timestamp())
						assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
						switch aggMap["nvml.gpu.utilization"] {
						case "sum":
							assert.InDelta(t, float64(4), dp.DoubleValue(), 0.01)
						case "avg":
							assert.InDelta(t, float64(2), dp.DoubleValue(), 0.01)
						case "min":
							assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
						case "max":
							assert.InDelta(t, float64(3), dp.DoubleValue(), 0.01)
						}
						_, ok := dp.Attributes().Get("model")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("gpu_number")
						assert.False(t, ok)
						_, ok = dp.Attributes().Get("uuid")
						assert.False(t, ok)
					}
				}
			}
		})
	}
}
