apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelcol-google
  namespace: otelcol-google
  labels:
    k8s-app: otelcol-google
spec:
  selector:
    matchLabels:
      name: otelcol-google
  template:
    metadata:
      labels:
        name: otelcol-google
    spec:
      containers:
      - name: otelcol-google
        image: us-docker.pkg.dev/cloud-ops-agents-artifacts/google-cloud-opentelemetry-collector/otelcol-google:latest
        args:
        - "--config=/etc/otelcol-google/config.yaml" # OPTIONAL: Remove if you do not want to run the default pipelines
        - "--config=/etc/config/config.yaml"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /etc/config/
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: config
          items:
          - key: config.yaml
            path: config.yaml
