version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: v0.133.0

env:
  - LD_FLAGS=-s -w
  - CGO_ENABLED=1
  - BUILD_FLAGS=-trimpath
  - GOWORK=off

builds:
  - id: otelopscol-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: otelopscol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

  - id: otelopscol-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: otelopscol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

nfpms:
  - package_name: otelopscol
    contents:
      - src: otelopscol.service
        dst: /lib/systemd/system/otelopscol.service
      - src: otelopscol.conf
        dst: /etc/otelopscol/otelopscol.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/otelopscol/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - otelopscol-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: OpenTelemetry Collector binary used by the Ops Agent
    license: Apache 2.0
