version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: v0.145.0

env:
  - LD_FLAGS=-s -w
  - CGO_ENABLED=0 # TODO: CGO is not supported in goreleaser yet.
  - BUILD_FLAGS=-trimpath
  - GOWORK=off

builds:
  - id: otelopscol-linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: otelopscol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

  - id: otelopscol-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: otelopscol
    dir: _build
    ldflags:
      - "-s -w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"

nfpms:
  - package_name: otelopscol
    contents:
      - src: otelopscol.service
        dst: /lib/systemd/system/otelopscol.service
      - src: otelopscol.conf
        dst: /etc/otelopscol/otelopscol.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/otelopscol/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - otelopscol-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: OpenTelemetry Collector binary used by the Ops Agent
    license: Apache 2.0

archives:
  - id: "otelopscol-tarball"
    ids:
      - "otelopscol-linux"
      - "otelopscol-windows"
    formats:
      - "tar.gz"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
        - "zip"

signs:
  - cmd: cosign
    signature: ${artifact}.sig
    certificate: ${artifact}.pem
    args:
      - "sign-blob"
      - "--output-signature"
      - "${artifact}.sig"
      - "--output-certificate"
      - "${artifact}.pem"
      - "${artifact}"
      - "--yes"
    artifacts: archive
    env:
      - SIGSTORE_NO_CACHE=true
    output: true
