version: 2
project_name: opentelemetry-operations-collector

snapshot:
  version_template: v0.145.0

env:
  - GOWORK=off
  - CGO_ENABLED=0

builds:
  - id: otelopscol-linux
    env:
    - CGO_ENABLED=1
    
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    
    ldflags:
      - "-s"
      - "-w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"
    binary: otelopscol
    dir: _build

  - id: otelopscol-windows
    goos:
      - windows
    goarch:
      - amd64
    binary: otelopscol
    ldflags:
      - "-s"
      - "-w"
    flags:
      - "-trimpath"
      - "-buildvcs=false"
    dir: _build

nfpms:
  - package_name: otelopscol
    contents:
      - src: otelopscol.service
        dst: /lib/systemd/system/otelopscol.service
      - src: otelopscol.conf
        dst: /etc/otelopscol/otelopscol.conf
        type: config|noreplace
        file_info:
          mode: 0644
      - src: config.yaml
        dst: /etc/otelopscol/config.yaml
        type: config|noreplace
        file_info:
          mode: 0644
    scripts:
      preinstall: preinstall.sh
      postinstall: postinstall.sh
      preremove: preremove.sh
    overrides:
      rpm:
        dependencies:
          - /bin/sh
    ids:
      - otelopscol-linux
    formats:
      - deb
      - rpm
    umask: 0
    maintainer: Google Cloud Platform <google@google.com> # something better than this
    description: OpenTelemetry Collector binary used by the Ops Agent
    license: Apache 2.0
