// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by weaver. DO NOT EDIT.

package event

import (
	"context"

	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

// PolicyEvaluateErrorEventName is the event name for policy.evaluate.error.
const PolicyEvaluateErrorEventName = "policy.evaluate.error"

type policyEvaluateErrorEventConfig struct {
	level  zapcore.Level
	fields []zap.Field
}

// PolicyEvaluateErrorEventOption applies optional settings or attributes to a policy.evaluate.error event record.
type PolicyEvaluateErrorEventOption func(*policyEvaluateErrorEventConfig)

// WithPolicyEvaluateErrorEventContext attaches a context.Context to a policy.evaluate.error event record for trace correlation.
func WithPolicyEvaluateErrorEventContext(ctx context.Context) PolicyEvaluateErrorEventOption {
	return func(c *policyEvaluateErrorEventConfig) {
		c.fields = append(c.fields, zap.Any("context", ctx))
	}
}

// WithPolicyEvaluateErrorEventLevel sets the log level on a policy.evaluate.error event record.
func WithPolicyEvaluateErrorEventLevel(level zapcore.Level) PolicyEvaluateErrorEventOption {
	return func(c *policyEvaluateErrorEventConfig) {
		c.level = level
	}
}

// WithPolicyEvaluateErrorEventFields adds custom zap fields to a policy.evaluate.error event record.
func WithPolicyEvaluateErrorEventFields(fields ...zap.Field) PolicyEvaluateErrorEventOption {
	return func(c *policyEvaluateErrorEventConfig) {
		c.fields = append(c.fields, fields...)
	}
}

// RecordPolicyEvaluateErrorEvent records the "policy.evaluate.error" event.
//
// Recorded when an error occurs while evaluating a policy.
func RecordPolicyEvaluateErrorEvent(
	logger *zap.Logger,
	err error,
	policyID string,
	policySetRevisionID string,
	opts ...PolicyEvaluateErrorEventOption,
) {
	cfg := policyEvaluateErrorEventConfig{
		level: zapcore.ErrorLevel,
		fields: []zap.Field{
			zap.String("event.name", PolicyEvaluateErrorEventName),
			zap.String("policy.id", policyID),
			zap.String("policy.set.revision.id", policySetRevisionID),
		},
	}
	for _, opt := range opts {
		opt(&cfg)
	}
	var body string
	if err != nil {
		body = err.Error()
	}
	logger.Log(cfg.level, body, cfg.fields...)
}

// PolicySetInvalidEventName is the event name for policy.set.invalid.
const PolicySetInvalidEventName = "policy.set.invalid"

type policySetInvalidEventConfig struct {
	level  zapcore.Level
	fields []zap.Field
}

// PolicySetInvalidEventOption applies optional settings or attributes to a policy.set.invalid event record.
type PolicySetInvalidEventOption func(*policySetInvalidEventConfig)

// WithPolicySetInvalidEventContext attaches a context.Context to a policy.set.invalid event record for trace correlation.
func WithPolicySetInvalidEventContext(ctx context.Context) PolicySetInvalidEventOption {
	return func(c *policySetInvalidEventConfig) {
		c.fields = append(c.fields, zap.Any("context", ctx))
	}
}

// WithPolicySetInvalidEventLevel sets the log level on a policy.set.invalid event record.
func WithPolicySetInvalidEventLevel(level zapcore.Level) PolicySetInvalidEventOption {
	return func(c *policySetInvalidEventConfig) {
		c.level = level
	}
}

// WithPolicySetInvalidEventFields adds custom zap fields to a policy.set.invalid event record.
func WithPolicySetInvalidEventFields(fields ...zap.Field) PolicySetInvalidEventOption {
	return func(c *policySetInvalidEventConfig) {
		c.fields = append(c.fields, fields...)
	}
}

// RecordPolicySetInvalidEvent records the "policy.set.invalid" event.
//
// Recorded when a policy set is structurally invalid and cannot be applied.
func RecordPolicySetInvalidEvent(
	logger *zap.Logger,
	err error,
	policySetRevisionID string,
	opts ...PolicySetInvalidEventOption,
) {
	cfg := policySetInvalidEventConfig{
		level: zapcore.ErrorLevel,
		fields: []zap.Field{
			zap.String("event.name", PolicySetInvalidEventName),
			zap.String("policy.set.revision.id", policySetRevisionID),
		},
	}
	for _, opt := range opts {
		opt(&cfg)
	}
	var body string
	if err != nil {
		body = err.Error()
	}
	logger.Log(cfg.level, body, cfg.fields...)
}
