// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("googleservicecontrol")
	ScopeName = "github.com/GoogleCloudPlatform/opentelemetry-operations-collector/exporter/googleservicecontrolexporter"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
)
