# Systemd environment file for the otelcol-google-policy service

# Command-line options for the otelcol-google-policy service.
# Run `/usr/bin/otelcol-google-policy --help` to see all available options.
OTELCOL_OPTIONS="--config=/etc/otelcol-google-policy/config.yaml"
