FROM alpine:3.19 as certs
RUN apk --update add ca-certificates

FROM scratch

ARG USER_UID=10001
USER ${USER_UID}

COPY --from=certs /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --chmod=755 {{ .BinaryName }} /{{ .BinaryName }}
COPY config.yaml /etc/{{ .BinaryName }}/config.yaml
ENTRYPOINT ["/{{ .BinaryName }}"{{ range .FeatureGates }}, "--featuregate",  "{{ . }}"{{ end }}]
CMD ["--config", "/etc/{{ .BinaryName }}/config.yaml"]
