// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/google/go-cmp/cmp/cmpopts"
	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/confmap/confmaptest"
)

func TestMetricsBuilderConfig(t *testing.T) {
	tests := []struct {
		name string
		want MetricsBuilderConfig
	}{
		{
			name: "default",
			want: DefaultMetricsBuilderConfig(),
		},
		{
			name: "all_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					VarnishBackendConnectionCount:  MetricConfig{Enabled: true},
					VarnishBackendRequestCount:     MetricConfig{Enabled: true},
					VarnishCacheOperationCount:     MetricConfig{Enabled: true},
					VarnishClientRequestCount:      MetricConfig{Enabled: true},
					VarnishClientRequestErrorCount: MetricConfig{Enabled: true},
					VarnishObjectCount:             MetricConfig{Enabled: true},
					VarnishObjectExpired:           MetricConfig{Enabled: true},
					VarnishObjectMoved:             MetricConfig{Enabled: true},
					VarnishObjectNuked:             MetricConfig{Enabled: true},
					VarnishSessionCount:            MetricConfig{Enabled: true},
					VarnishThreadOperationCount:    MetricConfig{Enabled: true},
				},
				ResourceAttributes: ResourceAttributesConfig{
					VarnishCacheName: ResourceAttributeConfig{Enabled: true},
				},
			},
		},
		{
			name: "none_set",
			want: MetricsBuilderConfig{
				Metrics: MetricsConfig{
					VarnishBackendConnectionCount:  MetricConfig{Enabled: false},
					VarnishBackendRequestCount:     MetricConfig{Enabled: false},
					VarnishCacheOperationCount:     MetricConfig{Enabled: false},
					VarnishClientRequestCount:      MetricConfig{Enabled: false},
					VarnishClientRequestErrorCount: MetricConfig{Enabled: false},
					VarnishObjectCount:             MetricConfig{Enabled: false},
					VarnishObjectExpired:           MetricConfig{Enabled: false},
					VarnishObjectMoved:             MetricConfig{Enabled: false},
					VarnishObjectNuked:             MetricConfig{Enabled: false},
					VarnishSessionCount:            MetricConfig{Enabled: false},
					VarnishThreadOperationCount:    MetricConfig{Enabled: false},
				},
				ResourceAttributes: ResourceAttributesConfig{
					VarnishCacheName: ResourceAttributeConfig{Enabled: false},
				},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := loadMetricsBuilderConfig(t, tt.name)
			if diff := cmp.Diff(tt.want, cfg, cmpopts.IgnoreUnexported(MetricConfig{}, ResourceAttributeConfig{})); diff != "" {
				t.Errorf("Config mismatch (-expected +actual):\n%s", diff)
			}
		})
	}
}

func loadMetricsBuilderConfig(t *testing.T, name string) MetricsBuilderConfig {
	cm, err := confmaptest.LoadConf(filepath.Join("testdata", "config.yaml"))
	require.NoError(t, err)
	sub, err := cm.Sub(name)
	require.NoError(t, err)
	cfg := DefaultMetricsBuilderConfig()
	require.NoError(t, component.UnmarshalConfig(sub, &cfg))
	return cfg
}
