// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("varnish")
	ScopeName = "github.com/GoogleCloudPlatform/opentelemetry-operations-collector/receiver/varnishreceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
