# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

receivers:
  hostmetrics:
    collection_interval: 1s
    scrapers:
      cpu:
      filesystem:
      load:
      memory:
      network:
      paging:
      disk:
      process:
      processes:

processors:
  # perform custom transformations that aren't supported by the metricstransform processor
  agentmetrics/cloud-monitoring:
    # 1. combines resource process metrics into metrics with processes as labels
    # 2. splits "disk.io" metrics into read & write metrics
    # 3. creates utilization metrics from usage metrics

  # filter out metrics not currently supported by cloud monitoring
  filter/cloud-monitoring:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - system.network.dropped
          - system.filesystem.inodes.usage
          - system.paging.faults

exporters:
  logging:
  file:
    path: ./metrics.json

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [agentmetrics/cloud-monitoring, filter/cloud-monitoring]
      exporters: [file,logging]
