name: Presubmit

on:
  pull_request:
    branches:
      - master
env:
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.18
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          lfs: true
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.DEFAULT_GO_VERSION }}
          cache: true
      - name: Setup Go Environment
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - name: Install Tools
        run: make install-tools
      - name: Run presubmit
        run: make presubmit
      - name: Test GPU Support
        if: startsWith(matrix.os, 'ubuntu')
        run: GO_BUILD_TAGS=gpu make test
